import {mkdtemp,writeFile,readFile,stat,symlink,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';import {preparePaths} from '../renderer/prepare.mjs';
const root=await mkdtemp(join(tmpdir(),'mdx-fast-'));process.chdir(root);await writeFile('root.mdx','import Child from "./child.mdx"\n\n<Child />');await writeFile('child.mdx','# Child');await writeFile('other.mdx','# Other');let r=await preparePaths(['root.mdx','other.mdx'],{policy:'trusted'});assert.equal(r.prepared,2);const old=(await stat('.nift/mdx-prepared/other.mdx.json')).mtimeMs;r=await preparePaths(['root.mdx','other.mdx'],{policy:'trusted'});assert.equal(r.cached,2);await writeFile('child.mdx','# Edited');r=await preparePaths(['root.mdx','other.mdx'],{policy:'trusted'});assert.equal(r.prepared,1);assert.equal((await stat('.nift/mdx-prepared/other.mdx.json')).mtimeMs,old);assert.match(JSON.parse(await readFile('.nift/mdx-prepared/root.mdx.json')).html,/Edited/);await writeFile('child.mdx','import Root from "./root.mdx"\n\n<Root />');await assert.rejects(preparePaths(['root.mdx'],{policy:'trusted'}),/Cyclic/);console.log('PASS fast preparation cold/no-change/transitive edit/unrelated/cycle');

await writeFile('dynamic.mdx','{import("./other.mdx")}');await assert.rejects(preparePaths(['dynamic.mdx'],{policy:'trusted'}),/Dynamic/);
await writeFile('reexport.mdx','export {x} from "./other.mdx"');await assert.rejects(preparePaths(['reexport.mdx'],{policy:'trusted'}),/re-exports/);
await assert.rejects(preparePaths(['../outside.mdx'],{policy:'trusted'}),/relative/);
await assert.rejects(preparePaths(['other.mdx'],{}),/trusted/);
await writeFile('child.mdx','# Child');await writeFile('adapter.mjs','export function components({element}){return {Aside:({children})=>element("aside",{},children)}}');await writeFile('component.mdx','<Aside>Hi</Aside>');let opts={policy:'trusted',components:'adapter.mjs'};await preparePaths(['component.mdx'],opts);await writeFile('adapter.mjs','export function components({element}){return {Aside:({children})=>element("section",{},children)}}');r=await preparePaths(['component.mdx'],opts);assert.equal(r.prepared,1);assert.match(JSON.parse(await readFile('.nift/mdx-prepared/component.mdx.json')).html,/<section/);
if(process.platform!=='win32'){await symlink('child.mdx','alias.mdx');await writeFile('linked.mdx','import Child from "./alias.mdx"\n\n<Child />');await preparePaths(['linked.mdx'],{policy:'trusted'});const {unlink}=await import('node:fs/promises');await unlink('alias.mdx');await symlink('other.mdx','alias.mdx');r=await preparePaths(['linked.mdx'],{policy:'trusted'});assert.equal(r.prepared,1);assert.match(JSON.parse(await readFile('.nift/mdx-prepared/linked.mdx.json')).html,/Other/);}
console.log('PASS adapter edit, policy, escape, dynamic/reexport and symlink retarget');
